[build]
builder = "nixpacks"
buildCommand = "pnpm install && pnpm run build"

[deploy]
startCommand = "node --experimental-specifier-resolution=node --trace-warnings dist/index.js"
healthcheckPath = "/api/test"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production" 