/**
 * Dialog title_source — classifies named Dialogs vs auto-titled Chatter.
 * Matches findOrCreateKipDialog auto titles: `{Board} · {Frame} · {Mon D}`.
 */

export const DIALOG_TITLE_SOURCES = ['user_set', 'auto_generated', 'system_promoted'] as const

export type DialogTitleSource = (typeof DIALOG_TITLE_SOURCES)[number]

/** Auto title from kipDialogLifecycle: e.g. "Agent · conversation · Jun 28". */
const AUTO_DIALOG_TITLE_RE =
  /^[A-Za-z][\w\s]* · .+ · (?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) \d{1,2}$/

export function isAutoGeneratedDialogTitle(title: string | null | undefined): boolean {
  const trimmed = title?.trim() ?? ''
  if (!trimmed) return true
  return AUTO_DIALOG_TITLE_RE.test(trimmed)
}

export function inferDialogTitleSource(title: string | null | undefined): DialogTitleSource {
  return isAutoGeneratedDialogTitle(title) ? 'auto_generated' : 'user_set'
}

/** Nav / agent: Chatter = auto_generated; Dialog = user_set or system_promoted. */
export function isChatterTitleSource(source: string | null | undefined): boolean {
  return source === 'auto_generated' || source == null
}

export function isDialogNavTitleSource(source: string | null | undefined): boolean {
  return source === 'user_set' || source === 'system_promoted'
}

/**
 * Chronicle Document shell is Dialog state, not session state.
 * Only a human-named Dialog (`user_set`) owns a Document.
 * `system_promoted` was Chatter elevated by draft-attach — conversation, not Document.
 */
export function isDocumentBearingDialogTitleSource(
  source: string | null | undefined,
): boolean {
  return source === 'user_set'
}
