/**
 * Backfill Dialog title_source + retitle clear Chatter sessions when a better
 * title can be inferred from linked draft titles.
 *
 * Run AFTER nav restructure (title_source column + UI) is deployed.
 *
 *   cd apps/api && pnpm exec tsx src/scripts/categorize-dialog-chatter.ts
 *   cd apps/api && pnpm exec tsx src/scripts/categorize-dialog-chatter.ts --execute
 */
import 'dotenv/config';
import { prisma } from '@keeper/database';
import { inferDialogTitleSource, isAutoGeneratedDialogTitle } from '@keeper/shared';

const execute = process.argv.includes('--execute');

async function main(): Promise<void> {
  const dialogs = await prisma.dialog.findMany({
    where: { is_archived: false },
    select: {
      id: true,
      title: true,
      title_source: true,
      domain_id: true,
      drafts: {
        where: { status: { notIn: ['promoted', 'archived'] } },
        select: { id: true, title: true },
        orderBy: { updated_at: 'desc' },
        take: 3,
      },
    },
  });

  let classified = 0;
  let retitled = 0;
  let promoted = 0;

  for (const dialog of dialogs) {
    const inferred = inferDialogTitleSource(dialog.title);
    const nextSource =
      dialog.drafts.length > 0 && inferred === 'auto_generated'
        ? 'system_promoted'
        : inferred;

    let nextTitle = dialog.title;
    if (
      isAutoGeneratedDialogTitle(dialog.title)
      && dialog.drafts[0]?.title?.trim()
      && dialog.drafts[0].title.trim().length >= 3
    ) {
      nextTitle = dialog.drafts[0].title.trim().slice(0, 200);
    }

    const sourceChanged = nextSource !== dialog.title_source;
    const titleChanged = nextTitle !== dialog.title;
    if (!sourceChanged && !titleChanged) continue;

    classified += sourceChanged ? 1 : 0;
    if (titleChanged) retitled += 1;
    if (nextSource === 'system_promoted' && dialog.title_source === 'auto_generated') {
      promoted += 1;
    }

    console.log(
      `${execute ? 'APPLY' : 'DRY'} ${dialog.id}: source ${dialog.title_source}→${nextSource}`
        + (titleChanged ? `; title "${dialog.title}" → "${nextTitle}"` : ''),
    );

    if (execute) {
      await prisma.dialog.update({
        where: { id: dialog.id },
        data: {
          title_source: nextSource,
          ...(titleChanged ? { title: nextTitle } : {}),
        },
      });
    }
  }

  console.log(
    JSON.stringify(
      {
        execute,
        scanned: dialogs.length,
        sourceUpdates: classified,
        retitled,
        promotedFromChatter: promoted,
      },
      null,
      2,
    ),
  );
}

main()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
